Medication Item Card Component
Code-the-Dream-School/hh-team4-front pull request #19
Opened 2024-11-24 06:21 UTC by ogunsegun

## Description

The Medication Item Card includes:

Medication Name
Dosage or Description
Price
Image 
Actions (e.g., Add to Cart, View Details)

I have two Components medication and medicationitemCard

## Related Issue

_Provide a link to the related issue 

## Type of Changes

_Feature update/change/addition, bug fix, styling update, etc._

## Acceptance Criteria

_Include the checked-off acceptance criteria from the issue._

## Update Screenshots

_Provide screenshots of the view before and after the changes._

### Before

### After

## Testing Instructions

_In a list format, tell us how to test this PR._

## Learnings (Optional)

_Document any things you learned or 'gotchas' you experienced._

2024-11-25 17:57 UTC, GinaCastromonte requested changes
Please redo component as discussed on Slack.

2024-12-04 15:24 UTC, sarross88 commented
try running "npm run format" on this branch then resubmit, make sure the checks don't fail

2024-12-04 18:02 UTC, ogunsegun commented
> try running "npm run format" on this branch then resubmit, make sure the checks don't fail

ok

2024-12-04 18:02 UTC, ogunsegun commented
> Please redo component as discussed on Slack.

ok

2024-12-04 19:11 UTC, GinaCastromonte approved these changes

2024-12-04 19:15 UTC, GinaCastromonte commented
I fixed some of the ESLint issues, but there are still a few unused variables in the code that we can clean up. You might also want to remove some of those commented-out imports.

2024-12-04 22:41 UTC, ValeriGuerrero commented
Hey Segun, looking more are your code you will have to run a few commands on your terminal before you push again. You can take a look at Gina's instructions: https://www.canva.com/design/DAGWYIfFtGs/Noh6MmmRsau78Mh8maTvGQ/edit
Once you do that you'll be able to see everyone's code and you can add the MedicationItemCard to the paths instead. 
<img width="1024" alt="Screenshot 2024-12-04 at 4 16 13 PM" src="https://github.com/user-attachments/assets/ede41c08-981f-48fd-aed3-146d1eb8cbeb">
<img width="1024" alt="Screenshot 2024-12-04 at 4 15 20 PM" src="https://github.com/user-attachments/assets/0a6603c8-c6bf-462f-adf2-fbd7335f9897">

2024-12-05 06:36 UTC, ogunsegun commented
> I fixed some of the ESLint issues, but there are still a few unused variables in the code that we can clean up. You might also want to remove some of those commented-out imports.

am working on it , thanks

2024-12-05 06:38 UTC, ogunsegun commented
> Hey Segun, looking more are your code you will have to run a few commands on your terminal before you push again. You can take a look at Gina's instructions: https://www.canva.com/design/DAGWYIfFtGs/Noh6MmmRsau78Mh8maTvGQ/edit Once you do that you'll be able to see everyone's code and you can add the MedicationItemCard to the paths instead. <img alt="Screenshot 2024-12-04 at 4 16 13 PM" width="1024" src="https://private-user-images.githubusercontent.com/113244520/392589470-ede41c08-981f-48fd-aed3-146d1eb8cbeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODA4NDgsIm5iZiI6MTczMzM4MDU0OCwicGF0aCI6Ii8xMTMyNDQ1MjAvMzkyNTg5NDcwLWVkZTQxYzA4LTk4MWYtNDhmZC1hZWQzLTE0NmQxZWI4Y2JlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwNjM1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGQ5MTVkMDRhZTRmYzdjNDhmNmEyMjM0ZDE4YzliNDg3ODlmODE1M2VkZmFjYzRkODg1ZGFlOWJmZGVhZTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0bkCEWZXjSdC9Tm_bRe5kZjlIU1W-I4hrtFbN1WnVZg"> <img alt="Screenshot 2024-12-04 at 4 15 20 PM" width="1024" src="https://private-user-images.githubusercontent.com/113244520/392589475-0a6603c8-c6bf-462f-adf2-fbd7335f9897.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzODA4NDgsIm5iZiI6MTczMzM4MDU0OCwicGF0aCI6Ii8xMTMyNDQ1MjAvMzkyNTg5NDc1LTBhNjYwM2M4LWM2YmYtNDYyZi1hZGYyLWZiZDczMzVmOTg5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwNjM1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODYxYTU0MjM0M2UzOGFhNWRkM2Y4ZjA0ZjdhMDk1MTI3OGI0ODc4M2U3MGU5NmVhYjcxODEwZjY1YzE3ODk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oVrGE3Vt2BbBHw9YAr-ZieJdzPjNpiEFBB_A2MbhNV4">

ok i will do that, thanks

2025-01-10 22:19 UTC, closed without merging