Navigation state
Code-the-Dream-School/hh-team4-front pull request #34
Opened 2024-12-11 19:12 UTC by sarross88

## Description

-1 - Same as Register User branch, but I added useNavigation from react-router-dom to add conditioning to my buttons, I also added Login functionality and toast package, make sure you run npm install!!! Formatting was done as well.

2024-12-11 19:43 UTC, F-sh2019 approved these changes

2024-12-12 22:04 UTC, ValeriGuerrero approved these changes

2024-12-13 00:04 UTC, GinaCastromonte requested changes
The `text-transform: uppercase;` style on the input fields may cause the email or password to be submitted in all uppercase letters, which can result in login failures if the backend is case-sensitive.

2024-12-13 16:15 UTC, GinaCastromonte approved these changes
Great! Login and Register is working now.  However,   I noticed the 'login' button on the landing page goes to the register page.

2024-12-13 21:51 UTC, merged