CSS global variables added to global.css
Code-the-Dream-School/hh-team4-front pull request #9
Opened 2024-11-20 18:11 UTC by sarross88

## Description

_1) made a file called global.css, added global variables 

## Type of Changes

_2) File add, CSS added

2024-11-20 19:34 UTC, GinaCastromonte requested changes
Data.jsx should be changed to regular data.js file for static data

2024-11-22 18:35 UTC, devandres-tech commented
@sarross88 There appears to be some merge conflicts in main.jsx
cc @GinaCastromonte

2024-11-22 22:11 UTC, GinaCastromonte approved these changes

2024-11-22 22:12 UTC, GinaCastromonte approved these changes

2024-11-23 03:17 UTC, ValeriGuerrero approved these changes

2024-11-23 03:17 UTC, merged